baseURL = 'https://crocidb.com/'

languageCode = 'en-us'
title = "Bruno Croci"

theme = 'pixyll'
contentdir = "content"
publishdir = "public"
builddrafts = false
canonifyurls = true

[markup]
  [markup.goldmark]
      [markup.goldmark.renderer]
            unsafe = true

[indexes]
  category = "categories"
  tag = "tags"

[params]
  author = "Bruno Croci"
  authorWebsite = "https://bruno.croci.me/"
  description = "I write about programming, gamedev, hacking projects, creative code, photography and my thoughts about anything that I like."
  homeIntro = """Hi. I'm **Bruno Croci**, also known online as **crocidb**, programmer and hobbist artist based in Düsseldorf, Germany. I'm a tinkerer who loves to create stuff. My main interestest are *video games*, *music*, *photography* and *programming* in general. 

Go to [/about](/about) for more info, [/now](/now) for what I'm currently up to, or check [Things I've Made](/things-ive-made) for a list of projects."""
  news = "Getting ready for OpenHardwareSummit 2026 in Berlin!"
  keywords = "programming, gamedev, hacking, coding, photography, thoughts"
  
  umami_website_id = "675a5b6c-b514-43a8-b0fc-cee8b6a1fd19"
  twitter_username = "CrociDB"
  paginate = 10
  
